#!/usr/bin/env bash

set -eo pipefail

if is_running wsl; then
  lg "Running in WSL, skipping waybar setup"
  exit 0
fi

if is_running ci; then
  lg "Running in CI, skipping waybar setup"
  exit 0
fi

lg "Linking waybar configs"
mkdir -p ~/.config/waybar/
ln -sf ~/dotfiles-arch/waybar/style.css ~/.config/waybar/style.css
ln -sf ~/dotfiles-arch/waybar/config.json ~/.config/waybar/config.json
