#!/usr/bin/env bash

set -eo pipefail

lg "Linking waybar configs"
mkdir -p ~/.config/waybar/
ln -sf ~/dotfiles-arch/waybar/style.css ~/.config/waybar/style.css
ln -sf ~/dotfiles-arch/waybar/config.json ~/.config/waybar/config.json
