#!/usr/bin/env bash

set -eo pipefail

if is_running wsl; then
  lg "Running in WSL, skipping DNS configuration"
  exit 0
fi

dir=~/dotfiles-arch/sway

mkdir -p ~/Screenshots
sudo pacman -S --noconfirm - < $dir/pacman.txt
