#!/usr/bin/env bash

set -eo pipefail

if is_running wsl; then
  lg "Running in WSL, skipping sway setup"
  exit 0
fi

if is_running ci; then
  lg "Running in CI, skipping sway setup"
  exit 0
fi

dir=~/dotfiles-arch/sway

mkdir -p ~/Screenshots
sudo pacman -S --noconfirm - < $dir/pacman.txt
