#!/usr/bin/env bash

set -eo pipefail

. "$HOME"/dotfiles-arch/qutebrowser/helpers.sh

if is_running ci; then
    lg "Qutebrowser: skipping setup in CI"
    exit 0
fi

lg "Qutebrowser: link config files"
link_config

lg "Qutebrowser: link bookmarks"
link_bookmarks

lg "Qutebrowser: link userscripts"
link_userscripts
